### ISSUE TITLE
Static site hosting on GitHub

### ISSUE THREAD

**Issue by denilsonsa** [graememcc/micropolisJS#24]
It seems most (all?) of this project can be served from a static website, or even run locally. Maybe you should consider creating a `gh-pages` branch on this repository, just to serve content using GitHub Pages: https://pages.github.com/

It is easy, requires essentially zero maintenance, and it will be kept online as long as the repository is also online.

**Comment by davidwesst** [comment]
I can confirm that it can run locally without any issue. Great idea!

**Comment by graememcc** [comment]
Hi folks.

Apologies, have been having a rather tough time of late - as witnessed by my domain's unavailability. Having been reduced to often wondering where the next meal is coming from has necessarily sank micropolisJS down my priority list for the moment; I'll be back giving it my full attention in better times.

For the moment, I've taken your advice. Thanks for the tip, @denilsonsa! The game should now be available at http://graememcc.github.io/micropolisJS/

Happy simming!

**Comment by denilsonsa** [comment]
@graememcc , may I suggest you fixing the README so that it points to the new URL? ;)

And, sure, rough times happen, and MicropolisJS should be indeed a low priority for you. You did the right thing. :)

**Comment by graememcc** [comment]
Good point about the README. Pushed commit 26cea83e62a.
